---
# defaults file for docker-engine
docker_keyserver: hkp://p80.pool.sks-keyservers.net:80
docker_repo_key: "58118E89F3A912897C070ADBF76221572C52609D"
docker_repo: http://apt.dockerproject.org/repo
docker_engine_version: "1.12.3"
docker_py_version: "1.10.6"
docker_requests_version: "2.12.1"
