---

# we are going to re-configure jenkins on every initialization !
# See: https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script

- name: "Create Jenkins init script dir"
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner:  "{{ jenkins_runas_user }}"
    group:  "{{ jenkins_runas_group }}"
    mode: 0755
  become: true

- template:
    src: "{{ item }}.j2"
    dest: "{{ jenkins_init_dir }}/{{ item }}"
    owner:  "{{ jenkins_runas_user }}"
    group:  "{{ jenkins_runas_group }}"
  with_items:
    - install_plugins.groovy
  tags:
    - gen
#    - get_creds.groovy
#    - set_git_global_config.groovy
#    - nexuus-artifactory-settings.groovy
