---


- name: "Update APT Cache"
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install OS Dependencies
  apt:
    name: "{{ item }}"
    state: installed
  become: true
  with_items:
    - python-httplib2
    - acl

- name: Jenkins APT Key
  apt_key:
    url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
  become: true

- name: Jenkins APT Repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
#    repo: "deb https://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: yes
  become: true

- name: Jenkins Install
  apt:
    name: jenkins
#    name: jenkins="{{ jenkins_version }}"
    # Setting this to 'latest' is perhaps debatable, but it seems silly not to
    # since this plugin also updates all of the Jenkins plugins automatically.
    state: latest
  become: true

- name: "Set permissions"
  file:
    path: "{{ item }}"
    recurse: yes
    owner: "{{ jenkins_user }}"
  with_items:
  - "/var/lib/jenkins"
  - "/var/log/jenkins"
  - "/var/cache/jenkins"
