---

- hosts: localhost
  become: true
  roles:
    - role: ansible-role-devenv
      tags: devenv

    - role: oracle-java
      tags: java

- hosts: localhost
  become: true
  roles:
    - role: docker
      tags: docker

    - role: ansible-role-docker-gitlab
      tags: gitlab

    - role: jenkins
      tags: jenkins
